E-Eletronicos/ECommerce/Controllers/AdminController.cs
using ECommerce.Modelo.DB;
using ECommerce.Modelo.DB.Model;
using ECommerce.Modelo.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult AreaAdministrador()
        {
            return View();
        }

        public ActionResult ControleUsuarios()
        {
            var usuarios = DbFactory.Instance.ClienteRepository.FindAll();

            return View(usuarios);
        }

        public ActionResult EditarCliente(Guid id)
        {
            var cliente = DbFactory.Instance.ClienteRepository.FindById(id);

            if (cliente != null)
            {
                return View(cliente);
            }
            else
            {
                return RedirectToAction("ControleUsuarios");
            }
        }

        public ActionResult DetalhesCliente(Guid id)
        {
            var cliente = DbFactory.Instance.ClienteRepository.FindById(id);

            return View(cliente);
        }

        public ActionResult ApagarCliente(Guid id)
        {
            var cliente = DbFactory.Instance.ClienteRepository.FindById(id);

            var login = DbFactory.Instance.LoginRepository.FindById(cliente.login.idLogin);

            if (cliente != null)
                DbFactory.Instance.ClienteRepository.Delete(cliente);

            if (login != null)
                DbFactory.Instance.LoginRepository.Delete(login);

            return RedirectToAction("ControleUsuarios");
        }
    }
}

E-Eletronicos/ECommerce/Controllers/CarrinhoController.cs
using ECommerce.Modelo.DB;
using ECommerce.Modelo.DB.Model;
using ECommerce.Modelo.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.Controllers
{
    public class CarrinhoController : Controller
    {
        public  static IList<Carrinho> Carrinho = new List<Carrinho>();

        // GET: Carrinho
        public ActionResult MeuCarrinho()
        {
            if (LoginUtils.Cliente != null)
            {
                var carrinho = DbFactory.Instance.CarrinhoRepository.PorCliente(LoginUtils.Cliente.idCliente);
                return View(carrinho);
            }
            else
            {
                return View(Carrinho);
            }
        }

        public ActionResult ColocarProdutoCarrinho(Guid id,int qtd)
        {
            var produto = DbFactory.Instance.ProdutoRepository.FindById(id);
            Carrinho carrinho = new Carrinho();
            carrinho.Id = Guid.NewGuid();
            carrinho.quantidade = qtd;
            carrinho.produto = produto;

            if (LoginUtils.Cliente != null)
            {
                carrinho.Id = new Guid();
                carrinho.cliente = LoginUtils.Cliente;
                DbFactory.Instance.CarrinhoRepository.SaveOrUpdate(carrinho);
            }

            Carrinho.Add(carrinho);

            LoginUtils.MeuCarrinho(Carrinho);

            return RedirectToAction("MeuCarrinho");
        }

        public ActionResult DetalhesProdutoCarrinho(Guid id)
        {
            Produto prod = DbFactory.Instance.ProdutoRepository.FindById(id);

            return View(prod);
        }

        public ActionResult AtualizarProdutoCarrinho(Guid id, int qtd)
        {
            var produto = DbFactory.Instance.ProdutoRepository.FindById(id);

            Carrinho Aux = new Carrinho();

            foreach(Carrinho c in Carrinho)
            {
                if(produto.Id == c.produto.Id)
                {
                    Aux = c;
                }
            }

            Carrinho.Remove(Aux);
            Aux.quantidade = qtd;
            Aux.produto = produto;
            Carrinho.Add(Aux);

            LoginUtils.MeuCarrinho(Carrinho);

            return RedirectToAction("MeuCarrinho");
        }

        public ActionResult ApagarProdutoCarrinho(Carrinho carrinho)
        {
            if (LoginUtils.Cliente != null)
            {
                DbFactory.Instance.CarrinhoRepository.Delete(carrinho);
            }
            else
            {
                Carrinho produto = new Carrinho();

                foreach(Carrinho c in Carrinho)
                {
                    if(c.Id == carrinho.Id)
                    {
                        produto = c;
                    }
                }

                Carrinho.Remove(produto);
            }

            LoginUtils.MeuCarrinho(Carrinho);

            return RedirectToAction("MeuCarrinho");
        }
    }
}

E-Eletronicos/ECommerce/Controllers/FabricanteController.cs
using ECommerce.Modelo.DB;
using ECommerce.Modelo.DB.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.Controllers
{
    public class FabricanteController : Controller
    {

        public static Produto Produto = new Produto();

        public void BuscarProduto(Guid id)
        {
            Produto = DbFactory.Instance.ProdutoRepository.FindById(id);
        }

        public ActionResult ControleFabricantes()
        {
            var fabricantes = DbFactory.Instance.FabricanteRepository.FindAll();

            return View(fabricantes);
        }

        public ActionResult DetalhesFabricante(Guid id)
        {
            var fab = DbFactory.Instance.FabricanteRepository.FindById(id);

            return View(fab);
        }

        public ActionResult InserirFabricante()
        {
            return View("EditarFabricante", new Fabricante());
        }

        public ActionResult GravarFabricante(Fabricante fab)
        {
            DbFactory.Instance.FabricanteRepository.SaveOrUpdate(fab);

            return RedirectToAction("ControleFabricantes");
        }

        public ActionResult EditarFabricante(Guid id)
        {
            var fab = DbFactory.Instance.FabricanteRepository.FindById(id);

            if (fab != null)
            {
                return View(fab);
            }
            else
            {
                return RedirectToAction("ControleFabricantes");
            }
        }

        public ActionResult ApagarFabricante(Guid id)
        {
            var fab = DbFactory.Instance.FabricanteRepository.FindById(id);

            if (fab != null)
                DbFactory.Instance.FabricanteRepository.Delete(fab);

            return RedirectToAction("ControleFabricantes");
        }

        public ActionResult InserirFabricanteNoProduto(Fabricante fab)
        {
            Produto prod = new Produto();

            prod.fabricante = fab;

            return View(prod);
        }

        public ActionResult SetarFabricanteProduto(Guid id)
        {
            var fabricante = DbFactory.Instance.FabricanteRepository.FindById(id);
            Produto.fabricante = fabricante;

            DbFactory.Instance.ProdutoRepository.SaveOrUpdate(Produto);

            return RedirectToAction("ControleProdutos","Produto");
        }
    }
}

E-Eletronicos/ECommerce/Controllers/ProdutoController.cs
using ECommerce.Modelo.DB;
using ECommerce.Modelo.DB.Model;
using ECommerce.Modelo.Utils;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.Controllers
{
    public class ProdutoController : Controller
    {
        // GET: Produto
        public ActionResult ControleProdutos()
        {
            var produto = DbFactory.Instance.ProdutoRepository.FindAll();

            return View(produto);
        }

        public ActionResult DetalhesProduto(Guid id)
        {
            var produto = DbFactory.Instance.ProdutoRepository.FindById(id);

            return View(produto);
        }

        public ActionResult DetalhesProdutoCliente(Guid id)
        {
            var produto = DbFactory.Instance.ProdutoRepository.FindById(id);

            return View(produto);
        }

        public ActionResult InserirProduto()
        {
            return View("EditarProduto",new Produto());
        }

        public ActionResult GravarProduto(Produto produto, HttpPostedFileBase imagem)
        {
            var caminho = "";

            if (imagem != null && imagem.ContentLength > 0)
            {
                caminho = Path.Combine(HttpContext.Server.MapPath("~/Images/Produtos/"), imagem.FileName);

                imagem.SaveAs(caminho);

                produto.Imagem = imagem.FileName;
            }

            DbFactory.Instance.ProdutoRepository.SaveOrUpdate(produto);

            return RedirectToAction("ControleProdutos");
        }

        public ActionResult EditarProduto(Guid id)
        {
            var produto = DbFactory.Instance.ProdutoRepository.FindById(id);

            if (produto != null)
            {
                return View(produto);
            }
            else
            {
                return RedirectToAction("ControleProdutos");
            }
        }

        public ActionResult ApagarProduto(Guid id)
        {
            var produto = DbFactory.Instance.ProdutoRepository.FindById(id);

            if (produto != null)
                DbFactory.Instance.ProdutoRepository.Delete(produto);

            return RedirectToAction("ControleProdutos");
        }

        public ActionResult VenderProduto()
        {          
            var cliente = DbFactory.Instance.ClienteRepository.FindById(LoginUtils.Cliente.idCliente);

            var lista = new Lista_Compra();
            lista.Cliente = cliente;
            var carrinho = DbFactory.Instance.CarrinhoRepository.PorCliente(LoginUtils.Cliente.idCliente);
            
            foreach(Carrinho c in carrinho)
            {
                lista.Produtos.Add(c.produto);
            }

                foreach (var prod in lista.Produtos)
                {
                   var produto =  DbFactory.Instance.ProdutoRepository.FindById(prod.Id);
                    produto.Estoque--;
                    DbFactory.Instance.ProdutoRepository.SaveOrUpdate(produto);
                }           
                

            return RedirectToAction("Index","Home",null);
        }



    }
}

E-Eletronicos/ECommerce/Views/Produto/ControleProdutos.cshtml
@model IEnumerable<ECommerce.Modelo.DB.Model.Produto>

@{
    ViewBag.Title = "ControleProdutos";
}

<h2>Controle de Produtos</h2>
<hr/>
<p>
    @Html.ActionLink("Novo Produto", "InserirProduto")
</p>
<table class="table">
    <tr>
        <th>
            Imagen
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Peso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Valor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estoque)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <!--Buscando a imagem para a exibição na view-->
            <img src="@Url.Content("~/Images/Produtos/" + item.Imagem)" height="100" width="100" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Peso)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Valor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estoque)
        </td>
        <td>
            @Html.ActionLink("Editar", "EditarProduto", new { id=item.Id }) |
            @Html.ActionLink("Detalhes", "DetalhesProduto", new { id=item.Id }) |
            @Html.ActionLink("Deletar", "ApagarProduto", new { id=item.Id })
        </td>
    </tr>
}
<hr/>
    <div>
        @Html.ActionLink("Area Administrador", "AreaAdministrador", "Admin")
    </div>

</table>

E-Eletronicos/ECommerce/Views/Produto/DetalhesProduto.cshtml
@model ECommerce.Modelo.DB.Model.Produto

@{
    ViewBag.Title = "DetalhesProduto";
}

<h2>Detalhes @Model.Nome</h2>

<div>
    <h4>Produto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Imagem
        </dt>
        <dd>
            <!--Buscando a imagem para a exibição na view-->
            <img src="@Url.Content("~/Images/Produtos/" + Model.Imagem)" height="200" width="200" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Peso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Peso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estoque)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estoque)
        </dd>

    </dl>
</div>

@Html.Action("BuscarProduto", "Fabricante", new { id = Model.Id })
@using (Html.BeginForm("ControleFabricantes", "Fabricante", FormMethod.Post))
{
    <div class="form-group">
        <div>
            <input type="submit" value="Selecionar Fabricante" class="btn btn-default" />
        </div>
    </div>
}

<p>
    @Html.ActionLink("Editar", "EditarProduto", new { id = Model.Id }) |
    @Html.ActionLink("Voltar a Lista", "ControleProdutos")
</p>

E-Eletronicos/ECommerce/Views/Produto/DetalhesProdutoCliente.cshtml
@model ECommerce.Modelo.DB.Model.Produto

@{
    ViewBag.Title = "DetalhesProdutoCliente";
}

<h2>Detalhes @Model.Nome</h2>

<div>
    <h4>Produto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Imagem
        </dt>
        <dd>
            <!--Buscando a imagem para a exibição na view-->
            <img src="@Url.Content("~/Images/Produtos/" + Model.Imagem)" height="300" width="300" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Peso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Peso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <td>
            @using (Html.BeginForm("ColocarProdutoCarrinho", "Carrinho", new { id = Model.Id }))
            {
                <dt>
                    Quantidade
                </dt>

                <dd>
                    <input type="text" class="form-control" id="qtd" name="qtd" value="1" />
                </dd>

                <br />

                <dd>
                    <button style="width:50%" align="center" class="botao btn btn-success btn-md" type="submit">Adicionar ao Carrinho</button>
                </dd>
            }
        </td>



    </dl>
</div>
<p>
    @Html.ActionLink("Voltar", "Index","Home")
</p>

E-Eletronicos/ECommerce/Views/Produto/EditarProduto.cshtml
@model ECommerce.Modelo.DB.Model.Produto

@{
    ViewBag.Title = "EditarProduto";
}

<h2>Produto</h2>

@using (Html.BeginForm("GravarProduto", "Produto", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Peso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estoque, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estoque, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estoque, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="imagem" name="imagem" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ControleProdutos")
</div>

E-Eletronicos/ECommerce/Views/Produto/InserirProduto.cshtml
@model ECommerce.Modelo.DB.Model.Produto

@{
    ViewBag.Title = "InserirProduto";
}

<h2>Inserir Produto</h2>

@using (Html.BeginForm("GravarProduto", "Produto", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Produto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="imagem" name="imagem" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a Lista", "ControleProdutos")
</div>