E-Eletronicos/ECommerce/Controllers/ClienteController.cs
using ECommerce.Modelo.DB;
using ECommerce.Modelo.DB.Model;
using ECommerce.Modelo.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.Controllers
{ 
    public class ClienteController : Controller
    {
        public static Login Login = new Login();
        public static Cliente Cliente = new Cliente();

        public void BuscarCliente(Guid id)
        {
            Cliente = DbFactory.Instance.ClienteRepository.FindById(id);
        }

        // GET: Cliente
        public ActionResult CadastrarLoginCliente()
        {
            return View(new Login());
        }
        
        public ActionResult GravarLoginCliente(Login log)
        {
            Login = log;

            DbFactory.Instance.LoginRepository.SaveOrUpdate(log);

            return RedirectToAction("CadastrarCliente");
        }

        public ActionResult CadastrarCliente()
        {
            return View(new Cliente());
        }

        public ActionResult GravarCliente(Cliente cli)
        {
            cli.login = Login;
            Cliente = cli;

            DbFactory.Instance.ClienteRepository.SaveOrUpdate(cli);

            Login = null;

            return RedirectToAction("CadastrarEndereco");
        }

        public ActionResult CadastrarEndereco()
        {
            return View(new Endereco());
        }

        public ActionResult GravarEndereco(Endereco end)
        {
            end.cliente = Cliente;

            DbFactory.Instance.EnderecoRepository.SaveOrUpdate(end);

            Cliente = null;

            return RedirectToAction("Login","Home");
        }

        public ActionResult EnderecosCliente()
        {
            Guid id = Cliente.idCliente;

            var endereco = DbFactory.Instance.EnderecoRepository.FindAll();
            IList<Endereco> end = new List<Endereco>();

            foreach(Endereco e in endereco)
            {
                if(e.cliente != null && e.cliente.idCliente == id)
                {
                    end.Add(e);
                }
            } 

            return View(end);
        }

        public ActionResult Logar(String usuario, String senha)
        {
            LoginUtils.Logar(usuario, senha);

            if (LoginUtils.Login.permissao == true)
            {
                return RedirectToAction("AreaAdministrador", "Admin");
            }
            else if (LoginUtils.Login.permissao == false)
            {
                if(LoginUtils.Carrinho != null)
                {
                    foreach(Carrinho c in LoginUtils.Carrinho)
                    {
                        c.Id = new Guid();
                        c.cliente = LoginUtils.Cliente;
                        DbFactory.Instance.CarrinhoRepository.SaveOrUpdate(c);
                    }
                }

                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        public ActionResult Deslogar()
        {
            Cliente = null;
            LoginUtils.Deslogar();
            return RedirectToAction("Index","Home");
        }

        public ActionResult PreencherQuestionario()
        {
            return View(new Questionario());
        }

        public ActionResult GravarQuestionario(Questionario quest)
        {
            quest.Cliente = Cliente;

            DbFactory.Instance.QuestionarioRepository.SaveOrUpdate(quest);

            return RedirectToAction("Login", "Index");
        }

        public ActionResult HistoricoPesquisa()
        {
            Guid id = LoginUtils.Cliente.idCliente;

            var historico = DbFactory.Instance.HistoricoBuscaRepository.HistoricoDoCliente(id);

            return View(historico);
        }

        public ActionResult ApagarItemHistorico(HistoricoBusca hb)
        {
            DbFactory.Instance.HistoricoBuscaRepository.Delete(hb);

            return RedirectToAction("HistoricoPesquisa");
        }

        public ActionResult ApagarTodoHistorico()
        {
            Guid id = LoginUtils.Cliente.idCliente;
            
            DbFactory.Instance.HistoricoBuscaRepository.ApagarTodoHistorico(id);

            return RedirectToAction("Index","Home");
        }
    }
}

E-Eletronicos/ECommerce/Controllers/HomeController.cs
using ECommerce.Modelo.DB;
using ECommerce.Modelo.DB.Model;
using ECommerce.Modelo.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            var produto = DbFactory.Instance.ProdutoRepository.FindAll();

            return View(produto);
        }

        public ActionResult DetalhesProduto(Guid id)
        {
            var produto = DbFactory.Instance.ProdutoRepository.FindById(id);

            return View(produto);
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Buscar(String pesquisa,String tipo)
        {
            IList<Produto> produtos = new List<Produto>(); 

            if (String.IsNullOrEmpty(pesquisa))
            {
                return RedirectToAction("Index");
            }

            if(tipo == "descricao")
            {
                produtos = DbFactory.Instance.ProdutoRepository.BuscarPelaDescricao(pesquisa);
            }
            else if(tipo == "valor")
            {
                produtos = DbFactory.Instance.ProdutoRepository.BuscarPeloValor(Convert.ToDouble(pesquisa));
            }
            else if(tipo == "fabricante")
            {
                var fabricantes = DbFactory.Instance.FabricanteRepository.GetAllByName(pesquisa);

                foreach (Fabricante f in fabricantes)
                {
                    produtos = DbFactory.Instance.ProdutoRepository.BuscarPeloIdFabricante(f.IdFabricante);
                }
            }
            else
            {
                produtos = DbFactory.Instance.ProdutoRepository.GetAllByName(pesquisa);
            }

            if (LoginUtils.Cliente != null)
            {
                foreach (Produto p in produtos)
                {
                    HistoricoBusca historico = new HistoricoBusca();
                    historico.DataHota = DateTime.Now ;
                    historico.cliente = LoginUtils.Cliente;
                    historico.produto = p;
                    DbFactory.Instance.HistoricoBuscaRepository.SaveOrUpdate(historico);
                }
            }

            return View("Index", produtos);
        }
    }
}

E-Eletronicos/ECommerce/Controllers/ProdutoController.cs
using ECommerce.Modelo.DB;
using ECommerce.Modelo.DB.Model;
using ECommerce.Modelo.Utils;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ECommerce.Controllers
{
    public class ProdutoController : Controller
    {
        // GET: Produto
        public ActionResult ControleProdutos()
        {
            var produto = DbFactory.Instance.ProdutoRepository.FindAll();

            return View(produto);
        }

        public ActionResult DetalhesProduto(Guid id)
        {
            var produto = DbFactory.Instance.ProdutoRepository.FindById(id);

            return View(produto);
        }

        public ActionResult DetalhesProdutoCliente(Guid id)
        {
            var produto = DbFactory.Instance.ProdutoRepository.FindById(id);

            return View(produto);
        }

        public ActionResult InserirProduto()
        {
            return View("EditarProduto",new Produto());
        }

        public ActionResult GravarProduto(Produto produto, HttpPostedFileBase imagem)
        {
            var caminho = "";

            if (imagem != null && imagem.ContentLength > 0)
            {
                caminho = Path.Combine(HttpContext.Server.MapPath("~/Images/Produtos/"), imagem.FileName);

                imagem.SaveAs(caminho);

                produto.Imagem = imagem.FileName;
            }

            DbFactory.Instance.ProdutoRepository.SaveOrUpdate(produto);

            return RedirectToAction("ControleProdutos");
        }

        public ActionResult EditarProduto(Guid id)
        {
            var produto = DbFactory.Instance.ProdutoRepository.FindById(id);

            if (produto != null)
            {
                return View(produto);
            }
            else
            {
                return RedirectToAction("ControleProdutos");
            }
        }

        public ActionResult ApagarProduto(Guid id)
        {
            var produto = DbFactory.Instance.ProdutoRepository.FindById(id);

            if (produto != null)
                DbFactory.Instance.ProdutoRepository.Delete(produto);

            return RedirectToAction("ControleProdutos");
        }

        public ActionResult VenderProduto()
        {          
            var cliente = DbFactory.Instance.ClienteRepository.FindById(LoginUtils.Cliente.idCliente);

            var lista = new Lista_Compra();
            lista.Cliente = cliente;
            var carrinho = DbFactory.Instance.CarrinhoRepository.PorCliente(LoginUtils.Cliente.idCliente);
            
            foreach(Carrinho c in carrinho)
            {
                lista.Produtos.Add(c.produto);
            }

                foreach (var prod in lista.Produtos)
                {
                   var produto =  DbFactory.Instance.ProdutoRepository.FindById(prod.Id);
                    produto.Estoque--;
                    DbFactory.Instance.ProdutoRepository.SaveOrUpdate(produto);
                }           
                

            return RedirectToAction("Index","Home",null);
        }



    }
}

E-Eletronicos/ECommerce/Views/Home/DetalhesProduto.cshtml
@model ECommerce.Modelo.DB.Model.Produto

@{
    ViewBag.Title = "DetalhesProduto";
}

<h2>DetalhesProduto</h2>

<div>
    <h4>Produto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Peso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Peso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estoque)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estoque)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Voltar a Lista", "Index")
</p>

E-Eletronicos/ECommerce/Views/Home/Index.cshtml
@model IEnumerable<ECommerce.Modelo.DB.Model.Produto>

@{
    ViewBag.Title = "Index";
}

<STYLE>
    .jumbotron {
        background-image: url("C:\Users\Jessica\Desktop\ecommerceLogo.jpg");
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-color: #303333;
        background-position: center top;
        margin-bottom: 0;
    }

    .navbar {
        margin-bottom: 50px;
        border-radius: 0;
        background-color: #111111;
    }

    body {
        background-color: #f9f4f4;
    }

    .loja {
        background-color: #edeaea;
        width: 100%;
        background-image: url("imagens/loja.jpg");
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-position: center top;
    }

    .orcamento {
        display: block;
        text-align: center;
        color: #239bc6;
    }

    a {
        color: #999;
        padding-top: 15px;
        padding-bottom: 15px;
        line-height: 20px;
        margin-right: 10px;
    }

    .dropdown-content {
        display: none;
        position: fixed;
        background-color: #f9f9f9;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        z-index: 1;
    }

        .dropdown-content a {
            float: none;
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            text-align: left;
        }

            .dropdown-content a:hover {
                background-color: #ddd;
            }

    .dropbtn {
        font-size: 14px;
        border: none;
        outline: none;
        color: white;
        padding: 14px 16px;
        background-color: inherit;
        font-family: inherit;
        margin: 0;
    }

    .dropdown:hover .dropdown-content {
        display: block;
    }

    #flipkart-navbar {
        background-color: #428bca;
        color: #FFFFFF;
        border-radius: 10px;
    }

    .row1 {
        padding-top: 10px;
    }

    .row2 {
        padding-bottom: 20px;
    }

    .flipkart-navbar-input {
        padding: 11px 16px;
        border-radius: 2px 0 0 2px;
        border: 0 none;
        outline: 0 none;
        font-size: 15px;
        color:#000000;
        float:right;
    }

    .flipkart-navbar-button {
        background-color: #ffe11b;
        border: 1px solid #ffe11b;
        border-radius: 0 2px 2px 0;
        color: #565656;
        padding: 10px 0;
        height: 43px;
        cursor: pointer;
        float: right;
    }

    .flipkart-navbar-combo {
        padding: 12px 16px;
        border-radius: 2px 2px 2px 2px;
        border: 0 none;
        outline: 0 none;
        font-size: 15px;
        color: #000000;
        float: right;
        margin:0 12px;
    }

    .cart-button {
        background-color: #2469d9;
        box-shadow: 0 2px 4px 0 rgba(0, 0, 0, .23), inset 1px 1px 0 0 hsla(0, 0%, 100%, .2);
        padding: 10px 0;
        text-align: center;
        height: 41px;
        border-radius: 2px;
        font-weight: 500;
        width: 120px;
        display: inline-block;
        color: #FFFFFF;
        text-decoration: none;
        color: inherit;
        border: none;
        outline: none;
    }

        .cart-button:hover {
            text-decoration: none;
            color: #fff;
            cursor: pointer;
        }

    .cart-svg {
        display: inline-block;
        width: 16px;
        height: 16px;
        vertical-align: middle;
        margin-right: 8px;
    }

    .item-number {
        border-radius: 3px;
        background-color: rgba(0, 0, 0, .1);
        height: 20px;
        padding: 3px 6px;
        font-weight: 500;
        display: inline-block;
        color: #fff;
        line-height: 12px;
        margin-left: 10px;
    }

    .upper-links {
        display: inline-block;
        padding: 0 11px;
        line-height: 23px;
        font-family: 'Roboto', sans-serif;
        letter-spacing: 0;
        color: inherit;
        border: none;
        outline: none;
        font-size: 12px;
    }

    .dropdown {
        position: relative;
        display: inline-block;
        margin-bottom: 0px;
    }

        .dropdown:hover {
            background-color: #fff;
        }

            .dropdown:hover .links {
                color: #000;
            }

            .dropdown:hover .dropdown-menu {
                display: block;
            }

        .dropdown .dropdown-menu {
            position: absolute;
            top: 100%;
            display: none;
            background-color: #fff;
            color: #333;
            left: 0px;
            border: 0;
            border-radius: 0;
            box-shadow: 0 4px 8px -3px #555454;
            margin: 0;
            padding: 0px;
        }

    .links {
        color: #fff;
        text-decoration: none;
    }

        .links:hover {
            color: #fff;
            text-decoration: none;
        }

    .profile-links {
        font-size: 12px;
        font-family: 'Roboto', sans-serif;
        border-bottom: 1px solid #e9e9e9;
        box-sizing: border-box;
        display: block;
        padding: 0 11px;
        line-height: 23px;
    }

    .profile-li {
        padding-top: 2px;
    }

    .largenav {
        display: none;
    }

    .smallnav {
        display: block;
    }

    .smallsearch {
        margin-left: 15px;
        margin-top: 15px;
    }

    .menu {
        cursor: pointer;
    }



    /*Sidenav*/
    .sidenav {
        height: 100%;
        width: 0;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        background-color: #fff;
        overflow-x: hidden;
        transition: 0.5s;
        box-shadow: 0 4px 8px -3px #555454;
        padding-top: 0px;
    }

        .sidenav a {
            padding: 8px 8px 8px 32px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
            transition: 0.3s
        }

        .sidenav .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 36px;
            margin-left: 50px;
            color: #fff;
        }

    .sidenav-heading {
        font-size: 36px;
        color: #fff;
    }

    .corpo {
        margin-top: 30px;
    }

    h5 {
        padding-left: 10px;
        font-size: 16px;
        padding-bottom: 6px;
        color: #f68624;
        text-align: left;
        font-weight: bold;
    }

    .preco {
        padding-left: 10px;
        font-size: 14px;
        padding-bottom: 6px;
        color: #337ab7;
        text-align: left;
        font-weight: bold;
    }

    .buscar {
        float: left;
        margin-right: 50px;
    }
</STYLE>


<div class="navbar">
    <div class="dropdown">
        <button class="dropbtn">
            @Html.ActionLink("HARDWARE", "")
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            @Html.ActionLink("Controladoras  ", "")
            @Html.ActionLink("Rede Wireless ", "")
            @Html.ActionLink("SSD  ", "")
        </div>
        <button class="dropbtn">
            @Html.ActionLink("HARDWARE", "")
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            @Html.ActionLink("Controladoras  ", "")
            @Html.ActionLink("Rede Wireless ", "")
            @Html.ActionLink("SSD  ", "")
        </div>
        <button class="dropbtn">
            @Html.ActionLink("HARDWARE", "")
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            @Html.ActionLink("Controladoras  ", "")
            @Html.ActionLink("Rede Wireless ", "")
            @Html.ActionLink("SSD  ", "")
        </div>
        <button class="dropbtn">
            @Html.ActionLink("HARDWARE", "")
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            @Html.ActionLink("Controladoras  ", "")
            @Html.ActionLink("Rede Wireless ", "")
            @Html.ActionLink("SSD  ", "")
        </div>
        <button class="dropbtn">
            @Html.ActionLink("HARDWARE", "")
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            @Html.ActionLink("Controladoras  ", "")
            @Html.ActionLink("Rede Wireless ", "")
            @Html.ActionLink("SSD  ", "")
        </div>
        <button class="dropbtn">
            @Html.ActionLink("HARDWARE", "")
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            @Html.ActionLink("Controladoras  ", "")
            @Html.ActionLink("Rede Wireless ", "")
            @Html.ActionLink("SSD  ", "")
        </div>
        <button class="dropbtn">
            @Html.ActionLink("HARDWARE", "")
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-content">
            @Html.ActionLink("Controladoras  ", "")
            @Html.ActionLink("Rede Wireless ", "")
            @Html.ActionLink("SSD  ", "")
        </div>
    </div>

</div>


<div id="flipkart-navbar">
    <div class="container">
        <div class="row row2">
            <div class="flipkart-navbar-search smallsearch col-sm-11 col-xs-11">                    
                @using (Html.BeginForm("Buscar", "Home",FormMethod.Post))
                {
                <div>
                    <button type="submit" class="flipkart-navbar-button col-xs-1">
                        <svg width="15px" height="15px">
                            <path d="M11.618 9.897l4.224 4.212c.092.09.1.23.02.312l-1.464 1.46c-.08.08-.222.072-.314-.02L9.868 11.66M6.486 10.9c-2.42 0-4.38-1.955-4.38-4.367 0-2.413 1.96-4.37 4.38-4.37s4.38 1.957 4.38 4.37c0 2.412-1.96 4.368-4.38 4.368m0-10.834C2.904.066 0 2.96 0 6.533 0 10.105 2.904 13 6.486 13s6.487-2.895 6.487-6.467c0-3.572-2.905-6.467-6.487-6.467 "></path>
                        </svg>
                    </button>
                    <input class="flipkart-navbar-input col-sm-11 col-xs-9" name="pesquisa" id="pesquisa" type="text" placeholder="Pesquisar" />
                    @Html.Label("", htmlAttributes: new { @class = "control-label col-md-2" })
                    <select class="flipkart-navbar-combo" id="tipo" name="tipo">
                        <option value="nome">Nome</option>
                        <option value="descricao">Descrição</option>
                        <option value="valor">Valor</option>
                        <option value="fabricante">Fabricante</option>
                    </select>
                </div>
                }
            </div>
        </div>
    </div>
</div>

<div class="container corpo">
    <div class="row">
   @foreach (var item in Model)
   {
        <div class="col-sm-3">
            <div class="panel">
                <table width="100%">
                    <tr>
                        <td class="panel-body">
                            <img src="@Url.Content("~/Images/Produtos/" + item.Imagem)" height="200" width="200" />
                        </td>
                    </tr>
                    <tr>
                        <td class="panel-body">
                            <h5>  @Html.DisplayFor(modelItem => item.Nome)</h5>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="descProd">@Html.DisplayFor(modelItem => item.Descricao)</span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="preco"> R$: @Html.DisplayFor(modelItem => item.Valor)</span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @using (Html.BeginForm("DetalhesProdutoCliente", "Produto", new { id = item.Id }))
                            {
                                <button style="width:100%" class="botao btn btn-primary btn-md" type="submit">Detalhes</button>
                            }
                        </td>
                    </tr>
                </table>
            </div>
        </div>
       }
      
    </div>
</div>

<!--
-->

E-Eletronicos/ECommerce/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Logar</h2>

@using (Html.BeginForm("Logar", "Cliente", FormMethod.Post))
{
    <div class="form-group">
        <label for="User">Usuario</label>
        <input type="text" class="form-control" id="usuario" name="usuario" aria-describedby="usuario" placeholder="Entre com usuario">
    </div>

    <div class="form-group">
        <label for="Password">Senha</label>
        <input type="password" class="form-control" id="senha" name="senha" placeholder="Senha">
    </div>

    <button type="submit" class="btn btn-primary">Logar</button>
}